language: node_js
node_js:
  - '10'
install:
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https -y
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.0.0 -y
  - npm install autorest@latest -g
  - git clone https://github.com/Azure/autorest.incubator.git
  - cd autorest.incubator && npm install
script:
  - autorest --use=./autorest.incubator --powershell --input-file=nutanix.json
